## Basic numpy
- 1-D numpy array
- N-D array

In [1]:
import numpy as np

## 1-D

- convert list/ tuple to numpy array
- claim dtype when create array
- arange
- linespace
- logspace

In [2]:
L = [1,2,3]

In [3]:
arr1 = np.array(L)

In [4]:
arr1

array([1, 2, 3])

In [5]:
T = (4,5,6)

In [6]:
arr2 = np.array(T)

In [7]:
arr2

array([4, 5, 6])

In [8]:
arr1.dtype

dtype('int32')

In [9]:
arr3 = np.array([1,2,3,4],dtype = float)

In [10]:
arr3

array([1., 2., 3., 4.])

In [11]:
arr3.dtype

dtype('float64')

In [12]:
# astype makes a new object
arr3 = arr3.astype(np.int32)

In [13]:
arr3.dtype

dtype('int32')

In [14]:
a = arr3.astype(np.str0)

In [15]:
a

array(['1', '2', '3', '4'], dtype='<U11')

In [16]:
arr4 = np.arange(1,10,2)

In [17]:
arr4

array([1, 3, 5, 7, 9])

In [18]:
arr5 = np.linspace(1,10,5)

In [19]:
arr5

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [20]:
arr6 = np.logspace(0,9,10,base=3)

In [21]:
arr6

array([1.0000e+00, 3.0000e+00, 9.0000e+00, 2.7000e+01, 8.1000e+01,
       2.4300e+02, 7.2900e+02, 2.1870e+03, 6.5610e+03, 1.9683e+04])

## N-D
- convert N-D array from list
- ones
- zeros
- empty
- full
- identity
- eye

In [23]:
LL= [[1,2,3],[4,5,6],[7,8,9]]
arr7 = np.array(LL)

In [24]:
arr7

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
arr7.shape

(3, 3)

In [26]:
arr1

array([1, 2, 3])

In [27]:
arr2

array([4, 5, 6])

In [34]:
arr8 = np.arange(1,10)

In [37]:
arr8 = arr8.reshape(3,3)

In [38]:
arr8

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
arr9 = np.ones((4,4), dtype = 'float')

In [40]:
arr9

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [41]:
arr10 = np.zeros((4,4), dtype = 'float')

In [42]:
arr10

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [49]:
arr11 = np.empty((2,2))

In [50]:
arr11

array([[1., 2.],
       [3., 4.]])

In [51]:
arr12 = np.full((2,5),5)

In [52]:
arr12

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [53]:
arr13 = np.identity(3,dtype="float")

In [55]:
arr13

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:
arr14 = np.eye(3,6,1)

### Property
- ndim
- shape
- size
- itemsize
- nbytes


In [59]:
arr14

array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.]])

In [60]:
arr14.ndim

2

In [61]:
arr14.shape

(3, 6)

In [62]:
arr14.size

18

In [63]:
arr14.itemsize

8

In [64]:
arr14.nbytes

144

In [68]:
arr15 = arr14.T

In [69]:
arr15

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [72]:
arr15[1,0]

1.0

In [73]:
arr15[1:,1:]

array([[0., 0.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]])

In [74]:
arr15

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Search
- bool list
- index list
- multiple index lists
- iterator

In [76]:
arr16 = np.linspace(1,10,5)

In [78]:
arr16

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [80]:
boolist = [True, False,True,False,True]
arr17 = np.array(boolist)

In [81]:
arr17

array([ True, False,  True, False,  True])

In [82]:
arr18 = arr16[arr17]

In [83]:
arr18

array([ 1. ,  5.5, 10. ])

In [85]:
arr19 = np.arange(1,16,2)

In [86]:
arr19

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [94]:
i = np.array([[1,1],[3,4]])

In [95]:
arr20 = arr19[i]

In [96]:
arr20

array([[3, 3],
       [7, 9]])

In [97]:
arr19

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [109]:
arr21 = np.arange(12).reshape(3,4)

In [110]:
m = np.array([[1,1],[2,0]])

In [111]:
n = np.array([[2,0],[1,1]])

In [114]:
arr22 = arr21[m,n]

In [115]:
arr22

array([[6, 4],
       [9, 1]])

In [119]:
for x in np.nditer(arr21):
    print(x,end=",")

0,1,2,3,4,5,6,7,8,9,10,11,

### Concatenate
- concatenate
- hstack
- vstack

In [123]:
arr23 = np.array([[1,2,3],[1,2,3]])

In [124]:
arr24 = np.array([[4,5,6],[4,5,6]])

In [130]:
arr25 = np.concatenate((arr23,arr24),0)

In [131]:
arr25

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [4, 5, 6]])

In [134]:
arr26 = np.hstack((arr23,arr24))

In [135]:
arr26

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [137]:
arr27 = np.vstack((arr23,arr24))

In [138]:
arr27

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [4, 5, 6]])

### Split
- split
- hsplit
- vsplit

In [172]:
a = np.linspace(1,20,9)
b = a.reshape(3,3)
arr28 = np.split(a,3)
arr29 = np.split(a,[4,7])
arr30 = np.split(b,3,axis=1)

In [173]:
arr28

[array([1.   , 3.375, 5.75 ]),
 array([ 8.125, 10.5  , 12.875]),
 array([15.25 , 17.625, 20.   ])]

In [174]:
arr29

[array([1.   , 3.375, 5.75 , 8.125]),
 array([10.5  , 12.875, 15.25 ]),
 array([17.625, 20.   ])]

In [175]:
b

array([[ 1.   ,  3.375,  5.75 ],
       [ 8.125, 10.5  , 12.875],
       [15.25 , 17.625, 20.   ]])

In [176]:
arr30

[array([[ 1.   ],
        [ 8.125],
        [15.25 ]]),
 array([[ 3.375],
        [10.5  ],
        [17.625]]),
 array([[ 5.75 ],
        [12.875],
        [20.   ]])]

In [177]:
arr31 = np.hsplit(b,3)

In [178]:
arr31

[array([[ 1.   ],
        [ 8.125],
        [15.25 ]]),
 array([[ 3.375],
        [10.5  ],
        [17.625]]),
 array([[ 5.75 ],
        [12.875],
        [20.   ]])]

In [180]:
arr32 = np.vsplit(b,3)

In [181]:
arr32

[array([[1.   , 3.375, 5.75 ]]),
 array([[ 8.125, 10.5  , 12.875]]),
 array([[15.25 , 17.625, 20.   ]])]

### Operations
- ufunc
- random
- normal distribution
- sort
- sum
- max
- min 
- average
- unique

In [193]:
a = np.array([-1,-2,-3,-4])
ufun = np.frompyfunc(abs,1,1)
arr33 = ufun(a)
arr33

array([1, 2, 3, 4], dtype=object)

In [184]:
arr34 = np.random.rand(10)

In [185]:
arr34

array([0.36185089, 0.88700679, 0.59847476, 0.18094953, 0.5348248 ,
       0.43685576, 0.66907256, 0.00406788, 0.39497134, 0.68131748])

In [186]:
arr35 = np.random.rand(5,5)

In [187]:
arr35

array([[0.79218917, 0.63201583, 0.41099722, 0.87011863, 0.18169097],
       [0.70735748, 0.14375852, 0.09958825, 0.23870418, 0.43321308],
       [0.18968737, 0.50963982, 0.91567094, 0.934136  , 0.63222601],
       [0.82213392, 0.93959672, 0.09674751, 0.32451092, 0.05081584],
       [0.08918179, 0.95414359, 0.70366057, 0.98588908, 0.26822749]])

In [191]:
arr36 = np.random.randint(5,10,size=(3,2))

In [192]:
arr36

array([[6, 6],
       [5, 7],
       [6, 5]])

In [194]:
arr37 = np.random.randn(10)

In [195]:
arr37

array([ 0.25403918, -0.96813683,  0.6080864 ,  1.52792805,  0.12582685,
       -0.53951726, -0.99478686,  0.06380437,  0.8846029 ,  1.59543496])

In [196]:
arr38 = np.random.normal(1000,30,size=(3,3))

In [197]:
arr38

array([[ 967.57248066,  964.22511572, 1009.08262936],
       [1020.14166036,  994.30371509, 1052.80114839],
       [1034.61176902, 1011.42770733,  999.28650986]])

In [199]:
np.sort(arr38,axis=-1,kind='quicksort')

array([[ 964.22511572,  967.57248066, 1009.08262936],
       [ 994.30371509, 1020.14166036, 1052.80114839],
       [ 999.28650986, 1011.42770733, 1034.61176902]])

In [221]:
arr39 = np.arange(1,20,2).reshape(2,5)
print(arr39)
np.sum(arr39,axis=1)
arr39[0,0]=100
arr39[0,2] = 20
arr39

[[ 1  3  5  7  9]
 [11 13 15 17 19]]


array([[100,   3,  20,   7,   9],
       [ 11,  13,  15,  17,  19]])

In [222]:
np.amax(arr39)
np.amax(arr39, axis= 0)

array([100,  13,  20,  17,  19])

In [223]:
np.amax(arr39, axis= 1)

array([100,  19])

In [224]:
arr39.max()

100

In [225]:
np.amin(arr39)
np.amin(arr39, axis= 0)
arr39.min()

3

In [226]:
np.mean(arr39)
np.mean(arr39, axis= 0)
arr39.mean()

21.4

In [229]:
np.average(arr39,axis=0,weights=[0.2,0.8])

array([28.8, 11. , 16. , 15. , 17. ])

In [236]:
arr39[0,1]=100
arr39[1,0]=100
arr39

array([[100, 100,  20,   7,   9],
       [100,  13,  15,  17,  19]])

In [247]:
arr40 = np.array(['l','o','l','i','p'])
u,v = np.unique(arr10,return_index=True,axis=0)

In [248]:
u,v

(array(['i', 'l', 'o', 'p'], dtype='<U1'), array([3, 0, 1, 4], dtype=int64))

In [251]:
arr41 = np.array([[1,1,1],[1,1,1],[1,2,1]])

In [252]:
arr41

array([[1, 1, 1],
       [1, 1, 1],
       [1, 2, 1]])

In [254]:
u,v = np.unique(arr41,return_index=True,axis=0)

In [255]:
u,v

(array([[1, 1, 1],
        [1, 2, 1]]),
 array([0, 2], dtype=int64))

In [256]:
u,v = np.unique(arr41,return_index=True,axis=1)

In [257]:
u,v

(array([[1, 1],
        [1, 1],
        [1, 2]]),
 array([0, 1], dtype=int64))

### Extra

In [259]:
a = np.array([1,2,3,4,100,20,40,30,10,22,55])
arr43 = np.where(a<30,a,a-20)
arr43

array([ 1,  2,  3,  4, 80, 20, 20, 10, 10, 22, 35])

In [260]:
b = np.array([[1,2,3],[1,2,2],[3,3,1]])
b

array([[1, 2, 3],
       [1, 2, 2],
       [3, 3, 1]])

In [263]:
arr44 = np.where(b==1,b,b+2)
arr44

array([[1, 4, 5],
       [1, 4, 4],
       [5, 5, 1]])

In [264]:
np.linalg.det(arr44)

-15.0

In [265]:
np.linalg.inv(arr44)

array([[ 1.06666667, -1.4       ,  0.26666667],
       [-1.26666667,  1.6       , -0.06666667],
       [ 1.        , -1.        ,  0.        ]])

In [268]:
a = arr44@np.linalg.inv(arr44)
a

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00, -6.66133815e-16,  1.00000000e+00]])

In [278]:
np.savez('numSav',a = arr44,b= arr43)

In [279]:
data = np.load('numSav.npz')

In [280]:
data

In [281]:
data['a']

array([[1, 4, 5],
       [1, 4, 4],
       [5, 5, 1]])